# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "Installing Docker..."
sudo apt-get update
sudo apt-get remove docker docker-engine docker.io
echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg |  sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
sudo apt-get update
sudo apt-get install -y docker-ce
# Restart docker to make sure we get the latest version of the daemon if there is an upgrade
sudo service docker restart
# Make sure we can actually use docker as the vagrant user
sudo usermod -aG docker vagrant
sudo docker --version

# Packages required for nomad & consul
sudo apt-get install unzip curl vim -y

echo "Installing Nomad"
NOMAD_VERSION=1.1.0
cd /tmp/
curl -sSL https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip -o nomad.zip
unzip nomad.zip
sudo chown root:root nomad
sudo mv nomad /usr/local/bin/
sudo mkdir -p /etc/nomad.d
sudo chmod a+w /etc/nomad.d

echo "Installing Consul"
CONSUL_VERSION=1.9.6
cd /tmp/
curl -sSL https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip -o consul.zip
unzip consul.zip
sudo chown root:root consul
sudo mv consul /usr/local/bin/
sudo mkdir -p /etc/consul.d
sudo chmod a+w /etc/consul.d

# Set hostname's IP to made advertisement Just Work
sudo sed -i -e "s/.*nomad.*/$(ip route get 1 | awk '{print $NF;exit}') nomad/" /etc/hosts


for bin in cfssl cfssl-certinfo cfssljson
do
  echo "Installing $bin..."
  curl -sSL https://pkg.cfssl.org/R1.2/${bin}_linux-amd64 > /tmp/${bin}
  sudo install /tmp/${bin} /usr/local/bin/${bin}
done

SCRIPT

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('cluster.yaml')

Vagrant.configure(2) do |config|
    # Iterate through entries in YAML file
  servers.each do |servers|
    # Moving forward, we should mount the specific
    # config files needed...nothing more.
    # config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define servers["name"] do |srv|
      srv.vm.hostname = servers["hostname"]
      srv.vm.provision "shell", inline: $script, privileged: false
      if servers["name"] == "nomad-server"
        config.vm.network "forwarded_port", guest: 4646, host: 4646, auto_correct: true, host_ip: "0.0.0.0"
      end
        srv.vm.box = servers["box"]
        srv.vm.network "private_network", ip: servers["ip"]
        srv.vm.provider :virtualbox do |vb|
          vb.name = servers["name"]
          vb.memory = servers["ram"]
        end
      end
  end
end
